import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import Accesibility from "@/components/icons/Accesibility";
import Microfono from "@/components/icons/Microfono";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "IngSoft Lab",
  description: "Generated by create next app",
  icons: "/public/images/png/Logo.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <head>
          <link rel="shortcut icon" href="/Logo.svg" type="image/x-icon" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}

          <div className="z-[10] grid max-sm:w-screen min-h-min items-center fixed max-sm:bottom-0 max-sm:left-0 max-sm:h-[4dvh] max-sm:grid-rows-[4dvh_minmax(min-content,200px)] grid-cols-[1fr] max-sm:translate-y-[calc(100%-4dvh)] max-sm:hover:translate-y-0 sm:min-w-min sm:top-0 sm:right-0 sm:h-[100dvh] sm:translate-x-[calc(100%-3vw)] sm:hover:translate-x-[0] sm:grid-cols-[3vw_minmax(min-content,200px)] sm:grid-rows-[1fr]">
            <div className="relative -border-2 h-full flex flex-col min-w-min -min-h-min items-center justify-center translate-y-[1px] sm:translate-x-[1px] ">
              <div className="absolute border-black h-0 w-[50vw] max-sm:border-b-[4dvh] max-sm:[border-left:4vw_transparent_solid] max-sm:[border-right:4vw_transparent_solid] sm:[border-top:4vh_transparent_solid] sm:[border-bottom:4vh_transparent_solid] sm:h-[50vh] sm:w-0 sm:right-0 sm:top-0 sm:border-r-[3vw] sm:translate-y-[50%]"></div>
              <Accesibility
                className="h-[45%] sm:w-[45%] aspect-auto z-[10]"
                color="white"
                title=""
              />
            </div>
            <div className=" bg-black w-full h-full flex items-center justify-center flex-col p-4 hover text-white gap-4 cursor-pointer">
              <h2 className="text-[1.2rem] font-semibold">Comandos de Voz</h2>
              <Microfono className="w-[8rem] " color="white" title="" />
            </div>
          </div>
        </body>
      </html>
    </ViewTransitions>
  );
}
