import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

import ProviderStore from "@/store/Provider";
import NoSSRAccesibilityMenu from "@/components/shared/NoSSRAccesibilityMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "IngSoft Lab",
  description: "Generated by create next app",
  icons: "/images/svg/Logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <head>
          <link rel="shortcut icon" href="/Logo.svg" type="image/x-icon" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ProviderStore>
            {children}
            <NoSSRAccesibilityMenu />
          </ProviderStore>
        </body>
      </html>
    </ViewTransitions>
  );
}
